[package]
name = "minetest-worldmapper"
version = "0.2.0"
edition = "2021"

[dependencies]
minetestworld = "0.2"
async-std = "1"
futures = "0.3"
clap = {version = "3.1.0", features = ["derive"]}
image = {version = "0.24", default-features = false}
toml = "0.5"
serde_derive = "1.0"
serde = "1.0"
rayon = "1"

[target.'cfg(not(all(target_endian = "big", target_pointer_width = "32")))'.dependencies]
smartstring = {version = "0.2", features = ["serde"], optional = true}

[features]
default = ["png", "bmp"]
smartstr = ["minetestworld/smartstring", "smartstring"]
bmp = ["image/bmp"]
png = ["image/png"]
jpeg = ["image/jpeg_rayon"]
avif = ["image/avif"]

[profile.release]
lto = true
