name: Rust

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

env:
  RUST_BACKTRACE: full
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo build
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - name: Clippy
        run: cargo clippy -- -Dwarnings